# Generated by Django 5.2.5 on 2025-08-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DreamInterpretationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream', models.TextField(verbose_name='দেখা স্বপ্ন')),
                ('detailed', models.BooleanField(default=False, verbose_name='বিস্তারিত ব্যাখ্যা')),
                ('ask_sides', models.BooleanField(default=False, verbose_name='পার্শ্ব প্রতিক্রিয়া জিজ্ঞাসা')),
                ('last_interpretation', models.TextField(blank=True, null=True, verbose_name='পূর্ববর্তী ব্যাখ্যা')),
                ('interpretation_response', models.JSONField(verbose_name='ব্যাখ্যার ফলাফল')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
            ],
            options={
                'verbose_name': 'স্বপ্নের ব্যাখ্যার ইতিহাস',
                'verbose_name_plural': 'স্বপ্নের ব্যাখ্যার ইতিহাস',
                'ordering': ['-created_at'],
            },
        ),
    ]
