# Generated by Django 5.2.5 on 2025-09-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dream',
        ),
    ]
