# Generated by Django 5.2.5 on 2025-09-24 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0004_delete_dream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('questions', models.JSONField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('ultimate_interpretation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initial', 'Initial Interpretation Pending'), ('answered', 'Ultimate Interpretation Pending'), ('completed', 'Completed')], default='initial', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'text')},
            },
        ),
    ]
