# Generated by Django 5.2.5 on 2025-09-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'free'), ('premiun', 'premium'), ('platinum', 'platinum')], default='free', max_length=10),
        ),
    ]
