# Generated by Django 5.2.5 on 2025-09-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.FloatField(),
        ),
    ]
