# Generated by Django 5.2.5 on 2025-09-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_pricing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='user',
        ),
    ]
