# Generated by Django 5.2.5 on 2025-09-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_remove_pricing_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='name',
            new_name='user_plan',
        ),
        migrations.AlterField(
            model_name='pricing',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='feature',
            field=models.CharField(max_length=1500),
        ),
    ]
