# Generated by Django 5.2.5 on 2025-09-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_rename_name_pricing_user_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='feature',
            field=models.TextField(max_length=1500),
        ),
    ]
