# Generated by Django 5.2.5 on 2025-09-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_alter_pricing_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
