# Generated by Django 5.2.5 on 2025-09-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_delete_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type your feature', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='enable or not')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(max_length=1500)),
                ('price', models.FloatField()),
                ('features', models.ManyToManyField(related_name='plans', through='chatbot.PlanFeature', to='chatbot.feature')),
            ],
        ),
        migrations.AddField(
            model_name='planfeature',
            name='pricing_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.pricing'),
        ),
        migrations.AlterUniqueTogether(
            name='planfeature',
            unique_together={('pricing_plan', 'feature')},
        ),
    ]
