# Generated by Django 5.2.5 on 2025-10-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_feature_planfeature_pricing_planfeature_pricing_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='user_plan',
        ),
        migrations.AddField(
            model_name='pricing',
            name='billing_interval',
            field=models.CharField(choices=[('month', 'Per month'), ('year', 'Per year'), ('2year', 'Every 2 years')], default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='pricing',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='pricing',
            name='interval_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pricing',
            name='plan_type',
            field=models.CharField(choices=[('premium', 'Dream Premium'), ('platinum', 'Dream Platinum')], default='premium', max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='features',
            field=models.ManyToManyField(related_name='pricing_plans', through='chatbot.PlanFeature', to='chatbot.feature'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
