# Generated by Django 5.2.5 on 2025-10-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_remove_pricing_user_plan_pricing_billing_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Dream Premium'), ('platinum', 'Dream Platinum')], default='free', max_length=20),
        ),
    ]
