# Generated by Django 5.2.5 on 2025-10-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_subscription_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='description',
            field=models.TextField(),
        ),
    ]
