# Generated by Django 5.2.5 on 2025-08-21 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_expiry',
        ),
    ]
