# Generated by Django 5.2.5 on 2025-09-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('platinum', 'Platinum')], default='free', max_length=10),
        ),
    ]
